package Rakugan::Vocab;
# Generated from crates/pixie-capi/elements.toml by tools/gen.pl. Do not
# edit by hand; edit the table and run `tools/gen.pl`.
#
# The engine's vocabulary as data: the numbers both sides of the C face
# count with, every element with its keywords, and the keywords every
# element takes. The door's runtime writes an element from this; the
# translator reads the same rows to write the .pix.
use strict;
use warnings;
use utf8;

# What a handler is called with.
our %PAY = (none => 0, text => 1, bool => 2, int => 3, float => 4);
# The .pix type of a handler's parameter, and the payload's name at a .pix call site.
our %PAYLOAD_TYPE = (text => 'String', bool => 'Bool', int => 'Int', float => 'Float');
our %PAYLOAD_NAME = (text => 'text', bool => 'checked', int => 'index', float => 'value');

# The elements.
our %KIND = (
    text => 1,
    button => 2,
    text_field => 3,
    column => 4,
    row => 5,
    grid => 6,
    grid_cell => 7,
    stack => 8,
    scroll_view => 9,
    h_scroll_view => 10,
    data_table => 11,
    modal => 12,
    list_view => 13,
    table => 14,
    image => 15,
    svg => 16,
    bar_chart => 17,
    line_chart => 18,
    progress => 19,
    checkbox => 20,
    switch => 21,
    slider => 22,
    select => 23,
    radio_group => 24,
    segmented => 25,
    tab_bar => 26,
    number_field => 27,
    int_field => 28,
    link => 29,
    spinner => 30,
    spacer => 31,
    divider => 32,
    canvas => 33,
);

# The keyword arguments, numbered once across every element.
our %KEY = (
    width => 1,
    height => 2,
    min_width => 3,
    max_width => 4,
    disabled => 5,
    theme => 6,
    animate => 7,
    easing => 8,
    enter => 9,
    exit => 10,
    col_span => 11,
    row_span => 12,
    role => 13,
    a11y_label => 14,
    tooltip => 15,
    text => 16,
    size => 17,
    color => 18,
    align => 19,
    grow => 20,
    bold => 21,
    italic => 22,
    mono => 23,
    underline => 24,
    wrap => 25,
    max_lines => 26,
    background => 27,
    padding => 28,
    border_radius => 29,
    border_width => 30,
    border_color => 31,
    label => 32,
    on_click => 33,
    hover_background => 34,
    active_background => 35,
    basis => 36,
    value => 37,
    placeholder => 38,
    on_change => 39,
    on_submit => 40,
    multiline => 41,
    rows => 42,
    spacing => 43,
    columns => 44,
    open => 45,
    count => 46,
    row => 47,
    item_height => 48,
    virtualized => 49,
    widths => 50,
    selected => 51,
    on_select => 52,
    sort => 53,
    descending => 54,
    on_sort => 55,
    source => 56,
    data => 57,
    labels => 58,
    min => 59,
    max => 60,
    axis => 61,
    series => 62,
    colors => 63,
    indeterminate => 64,
    checked => 65,
    step => 66,
    options => 67,
    active => 68,
    url => 69,
    thickness => 70,
    scale => 71,
    palette => 72,
);

# The keywords every element takes. `presence` marks the four whose box
# is built because somebody wrote the property; `owned` names the element
# props that take the same word first.
our @RIDERS = (
    { name => 'width', type => 'num', key => 1, pix => 'width', presence => 1, owned => 'size,width' },
    { name => 'height', type => 'num', key => 2, pix => 'height', presence => 1, owned => 'size,height' },
    { name => 'min_width', type => 'num', key => 3, pix => 'minWidth', presence => 1 },
    { name => 'max_width', type => 'num', key => 4, pix => 'maxWidth', presence => 1 },
    { name => 'disabled', type => 'bool', key => 5, pix => 'disabled', default => 0 },
    { name => 'theme', type => 'str', key => 6, pix => 'theme', default => '' },
    { name => 'animate', type => 'num', key => 7, pix => 'animate', default => 0.0 },
    { name => 'easing', type => 'str', key => 8, pix => 'easing', default => '' },
    { name => 'enter', type => 'bool', key => 9, pix => 'enter', default => 0 },
    { name => 'exit', type => 'bool', key => 10, pix => 'exit', default => 0 },
    { name => 'col_span', type => 'int', key => 11, pix => 'colSpan', default => 1 },
    { name => 'row_span', type => 'int', key => 12, pix => 'rowSpan', default => 1 },
    { name => 'role', type => 'str', key => 13, pix => 'role', default => '' },
    { name => 'a11y_label', type => 'str', key => 14, pix => 'label', default => '', owned => 'label' },
    { name => 'tooltip', type => 'str', key => 15, pix => 'tooltip', default => '' },
);
our %RIDER = map { $_->{name} => $_ } @RIDERS;

# The elements, in the table's order: the kind, the .pix element, what
# it is (a container, a painter, one that sizes a side of its own, one
# whose own label is its accessible name), and its keywords in the
# order they are written to the engine.
our @ELEMENTS = (
    {
        name => 'text',
        kind => 1,
        pix => 'Text',
        native => 'width',
        doc => 'A run of text. `wrap` is "", "nowrap" or "ellipsis"; a background with padding and a radius makes a pill.',
        props => [
            { name => 'text', key => 16, type => 'str', pix => 'text', pos => 1 },
            { name => 'size', key => 17, type => 'num', pix => 'fontSize', default => 0.0 },
            { name => 'color', key => 18, type => 'str', pix => 'color', default => '' },
            { name => 'align', key => 19, type => 'str', pix => 'align', default => '' },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'bold', key => 21, type => 'bool', pix => 'bold', default => 0 },
            { name => 'italic', key => 22, type => 'bool', pix => 'italic', default => 0 },
            { name => 'mono', key => 23, type => 'bool', pix => 'mono', default => 0 },
            { name => 'underline', key => 24, type => 'bool', pix => 'underline', default => 0 },
            { name => 'wrap', key => 25, type => 'str', pix => 'wrap', default => '' },
            { name => 'max_lines', key => 26, type => 'int', pix => 'maxLines', default => 0 },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'background', key => 27, type => 'str', pix => 'background', default => '' },
            { name => 'padding', key => 28, type => 'num', pix => 'padding', default => 0.0 },
            { name => 'border_radius', key => 29, type => 'num', pix => 'borderRadius', default => 0.0 },
            { name => 'border_width', key => 30, type => 'num', pix => 'borderWidth', default => 0.0 },
            { name => 'border_color', key => 31, type => 'str', pix => 'borderColor', default => '' },
        ],
    },
    {
        name => 'button',
        kind => 2,
        pix => 'Button',
        native => 'size',
        primary => 'on_click',
        doc => 'A button. The block runs when it is pressed.',
        props => [
            { name => 'label', key => 32, type => 'str', pix => 'text', pos => 1 },
            { name => 'on_click', key => 33, handler => 'none', pix => 'onClick', payload => '' },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'size', key => 17, type => 'num', pix => 'fontSize', default => 0.0 },
            { name => 'background', key => 27, type => 'str', pix => 'background', default => '' },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'color', key => 18, type => 'str', pix => 'color', default => '' },
            { name => 'hover_background', key => 34, type => 'str', pix => 'hover.background', default => '' },
            { name => 'active_background', key => 35, type => 'str', pix => 'active.background', default => '' },
            { name => 'border_radius', key => 29, type => 'num', pix => 'borderRadius', default => 0.0 },
            { name => 'border_width', key => 30, type => 'num', pix => 'borderWidth', default => 0.0 },
            { name => 'border_color', key => 31, type => 'str', pix => 'borderColor', default => '' },
            { name => 'basis', key => 36, type => 'num', pix => 'basis', default => 0.0 },
        ],
    },
    {
        name => 'text_field',
        kind => 3,
        pix => 'TextField',
        primary => 'on_change',
        doc => 'A line a person types into. `on_change` fires per keystroke, `on_submit` when they press enter; `multiline` makes it a paragraph field.',
        props => [
            { name => 'value', key => 37, type => 'str', pix => 'text', pos => 1 },
            { name => 'placeholder', key => 38, type => 'str', pix => 'placeholder', default => '' },
            { name => 'on_change', key => 39, handler => 'text', pix => 'onTextChanged', payload => 'text' },
            { name => 'on_submit', key => 40, handler => 'text', pix => 'onSubmitted', payload => 'text' },
            { name => 'multiline', key => 41, type => 'bool', pix => 'multiline', default => 0 },
            { name => 'rows', key => 42, type => 'num', pix => 'rows', default => 0.0 },
        ],
    },
    {
        name => 'column',
        kind => 4,
        pix => 'Column',
        children => 1,
        doc => 'Its children down the page.',
        props => [
            { name => 'spacing', key => 43, type => 'num', pix => 'spacing', default => -1.0 },
            { name => 'padding', key => 28, type => 'num', pix => 'padding', default => 0.0 },
            { name => 'background', key => 27, type => 'str', pix => 'background', default => '' },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'border_radius', key => 29, type => 'num', pix => 'borderRadius', default => 0.0 },
            { name => 'border_width', key => 30, type => 'num', pix => 'borderWidth', default => 0.0 },
            { name => 'border_color', key => 31, type => 'str', pix => 'borderColor', default => '' },
        ],
    },
    {
        name => 'row',
        kind => 5,
        pix => 'Row',
        children => 1,
        doc => 'Its children across the page.',
        props => [
            { name => 'spacing', key => 43, type => 'num', pix => 'spacing', default => -1.0 },
            { name => 'padding', key => 28, type => 'num', pix => 'padding', default => 0.0 },
            { name => 'background', key => 27, type => 'str', pix => 'background', default => '' },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'border_radius', key => 29, type => 'num', pix => 'borderRadius', default => 0.0 },
            { name => 'border_width', key => 30, type => 'num', pix => 'borderWidth', default => 0.0 },
            { name => 'border_color', key => 31, type => 'str', pix => 'borderColor', default => '' },
        ],
    },
    {
        name => 'grid',
        kind => 6,
        pix => 'Grid',
        children => 1,
        doc => 'Its children on tracks. `columns` counts the tracks; `col_span` on a child covers more than one.',
        props => [
            { name => 'columns', key => 44, type => 'int', pix => 'columns', default => 2 },
            { name => 'rows', key => 42, type => 'int', pix => 'rows', default => 0 },
            { name => 'spacing', key => 43, type => 'num', pix => 'spacing', default => -1.0 },
            { name => 'padding', key => 28, type => 'num', pix => 'padding', default => 0.0 },
            { name => 'background', key => 27, type => 'str', pix => 'background', default => '' },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'border_radius', key => 29, type => 'num', pix => 'borderRadius', default => 0.0 },
            { name => 'border_width', key => 30, type => 'num', pix => 'borderWidth', default => 0.0 },
            { name => 'border_color', key => 31, type => 'str', pix => 'borderColor', default => '' },
        ],
    },
    {
        name => 'grid_cell',
        kind => 7,
        pix => 'GridCell',
        children => 1,
        doc => 'The span written out: this and `col_span:` on the child itself are the same tree.',
        props => [
        ],
    },
    {
        name => 'stack',
        kind => 8,
        pix => 'Stack',
        children => 1,
        doc => 'Its children on top of one another.',
        props => [
        ],
    },
    {
        name => 'scroll_view',
        kind => 9,
        pix => 'ScrollView',
        children => 1,
        native => 'height',
        doc => 'A pane that scrolls when its children do not fit.',
        props => [
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
        ],
    },
    {
        name => 'h_scroll_view',
        kind => 10,
        pix => 'HScrollView',
        children => 1,
        doc => 'A pane that scrolls sideways.',
        props => [
        ],
    },
    {
        name => 'data_table',
        kind => 11,
        pix => 'DataTable',
        children => 1,
        doc => 'The first `row` child is the header; the later ones are data rows, shaded in alternation, in a frame that comes with the element.',
        props => [
        ],
    },
    {
        name => 'modal',
        kind => 12,
        pix => 'Modal',
        children => 1,
        doc => 'A panel over the rest of the window while `open`.',
        props => [
            { name => 'open', key => 45, type => 'bool', pix => 'open', default => 1 },
        ],
    },
    {
        name => 'list_view',
        kind => 13,
        pix => 'ListView',
        native => 'height',
        doc => 'Rows built on demand: the builder is called for the rows in view, not for all of them.',
        props => [
            { name => 'count', key => 46, type => 'int', pix => 'count', pos => 1 },
            { name => 'row', key => 47, type => 'rows', pix => 'row', pos => 1 },
            { name => 'item_height', key => 48, type => 'num', pix => 'itemHeight', default => 24.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'virtualized', key => 49, type => 'bool', pix => 'virtualized', default => 1 },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
        ],
    },
    {
        name => 'table',
        kind => 14,
        pix => 'Table',
        native => 'height',
        doc => 'A table whose rows are built on demand, laid on tracks whose shares are `widths`. `on_select` receives the row clicked, `on_sort` the header.',
        props => [
            { name => 'columns', key => 44, type => 'strs', pix => 'columns', pos => 1 },
            { name => 'count', key => 46, type => 'int', pix => 'count', pos => 1 },
            { name => 'row', key => 47, type => 'rows', pix => 'row', pos => 1 },
            { name => 'widths', key => 50, type => 'nums', pix => 'widths', default => [] },
            { name => 'item_height', key => 48, type => 'num', pix => 'itemHeight', default => 24.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
            { name => 'selected', key => 51, type => 'int', pix => 'selected', default => -1 },
            { name => 'on_select', key => 52, handler => 'int', pix => 'onSelect', payload => 'index' },
            { name => 'sort', key => 53, type => 'int', pix => 'sort', default => -1 },
            { name => 'descending', key => 54, type => 'bool', pix => 'descending', default => 0 },
            { name => 'on_sort', key => 55, handler => 'int', pix => 'onSort', payload => 'index' },
        ],
    },
    {
        name => 'image',
        kind => 15,
        pix => 'Image',
        native => 'size',
        doc => 'A picture from a file.',
        props => [
            { name => 'source', key => 56, type => 'str', pix => 'source', pos => 1 },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
        ],
    },
    {
        name => 'svg',
        kind => 16,
        pix => 'Svg',
        native => 'size',
        doc => 'A drawing from an SVG file, painted at any size.',
        props => [
            { name => 'source', key => 56, type => 'str', pix => 'source', pos => 1 },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
        ],
    },
    {
        name => 'bar_chart',
        kind => 17,
        pix => 'BarChart',
        native => 'size',
        doc => 'Bars. `min`/`max` both 0 take the range from the data; `axis` draws ticks and gridlines; `series` draws several groups.',
        props => [
            { name => 'data', key => 57, type => 'nums', pix => 'data', pos => 1, default => [] },
            { name => 'labels', key => 58, type => 'strs', pix => 'labels', default => [] },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'min', key => 59, type => 'num', pix => 'min', default => 0.0 },
            { name => 'max', key => 60, type => 'num', pix => 'max', default => 0.0 },
            { name => 'axis', key => 61, type => 'bool', pix => 'axis', default => 0 },
            { name => 'color', key => 18, type => 'str', pix => 'color', default => '' },
            { name => 'series', key => 62, type => 'nums2', pix => 'series', default => [] },
            { name => 'colors', key => 63, type => 'strs', pix => 'colors', default => [] },
        ],
    },
    {
        name => 'line_chart',
        kind => 18,
        pix => 'LineChart',
        native => 'size',
        doc => 'A line. Same arguments as the bars, and `series` draws several lines.',
        props => [
            { name => 'data', key => 57, type => 'nums', pix => 'data', pos => 1, default => [] },
            { name => 'labels', key => 58, type => 'strs', pix => 'labels', default => [] },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'min', key => 59, type => 'num', pix => 'min', default => 0.0 },
            { name => 'max', key => 60, type => 'num', pix => 'max', default => 0.0 },
            { name => 'axis', key => 61, type => 'bool', pix => 'axis', default => 0 },
            { name => 'color', key => 18, type => 'str', pix => 'color', default => '' },
            { name => 'series', key => 62, type => 'nums2', pix => 'series', default => [] },
            { name => 'colors', key => 63, type => 'strs', pix => 'colors', default => [] },
        ],
    },
    {
        name => 'progress',
        kind => 19,
        pix => 'ProgressBar',
        native => 'size',
        owns_label => 1,
        doc => 'A track filled to `value` (0 to 1); `indeterminate` sweeps instead, for work with no known length.',
        props => [
            { name => 'value', key => 37, type => 'num', pix => 'value', pos => 1 },
            { name => 'width', key => 1, type => 'num', pix => 'width', default => 0.0 },
            { name => 'height', key => 2, type => 'num', pix => 'height', default => 0.0 },
            { name => 'label', key => 32, type => 'str', pix => 'label', default => '' },
            { name => 'indeterminate', key => 64, type => 'bool', pix => 'indeterminate', default => 0 },
        ],
    },
    {
        name => 'checkbox',
        kind => 20,
        pix => 'Checkbox',
        owns_label => 1,
        primary => 'on_change',
        doc => 'A box a person ticks. The block receives the new state.',
        props => [
            { name => 'label', key => 32, type => 'str', pix => 'label', pos => 1 },
            { name => 'checked', key => 65, type => 'bool', pix => 'checked', default => 0 },
            { name => 'on_change', key => 39, handler => 'bool', pix => 'onToggle', payload => 'checked' },
        ],
    },
    {
        name => 'switch',
        kind => 21,
        pix => 'Switch',
        owns_label => 1,
        primary => 'on_change',
        doc => 'A switch a person flips. The block receives the new state.',
        props => [
            { name => 'label', key => 32, type => 'str', pix => 'label', pos => 1 },
            { name => 'checked', key => 65, type => 'bool', pix => 'checked', default => 0 },
            { name => 'on_change', key => 39, handler => 'bool', pix => 'onToggle', payload => 'checked' },
        ],
    },
    {
        name => 'slider',
        kind => 22,
        pix => 'Slider',
        primary => 'on_change',
        doc => 'A track a person drags. The block receives the new number.',
        props => [
            { name => 'value', key => 37, type => 'num', pix => 'value', default => 0.0 },
            { name => 'min', key => 59, type => 'num', pix => 'min', default => 0.0 },
            { name => 'max', key => 60, type => 'num', pix => 'max', default => 1.0 },
            { name => 'step', key => 66, type => 'num', pix => 'step', default => 0.0 },
            { name => 'on_change', key => 39, handler => 'float', pix => 'onChange', payload => 'value' },
        ],
    },
    {
        name => 'select',
        kind => 23,
        pix => 'Select',
        primary => 'on_change',
        doc => 'A drop-down. The block receives the chosen index.',
        props => [
            { name => 'options', key => 67, type => 'strs', pix => 'options', default => [] },
            { name => 'selected', key => 51, type => 'int', pix => 'selected', default => 0 },
            { name => 'on_change', key => 39, handler => 'int', pix => 'onSelect', payload => 'index' },
        ],
    },
    {
        name => 'radio_group',
        kind => 24,
        pix => 'RadioGroup',
        primary => 'on_change',
        doc => 'A column of radio buttons. The block receives the chosen index.',
        props => [
            { name => 'options', key => 67, type => 'strs', pix => 'options', default => [] },
            { name => 'selected', key => 51, type => 'int', pix => 'selected', default => 0 },
            { name => 'on_change', key => 39, handler => 'int', pix => 'onSelect', payload => 'index' },
        ],
    },
    {
        name => 'segmented',
        kind => 25,
        pix => 'Segmented',
        primary => 'on_change',
        doc => 'A row of joined toggle buttons. The block receives the chosen index.',
        props => [
            { name => 'options', key => 67, type => 'strs', pix => 'options', default => [] },
            { name => 'selected', key => 51, type => 'int', pix => 'selected', default => 0 },
            { name => 'on_change', key => 39, handler => 'int', pix => 'onSelect', payload => 'index' },
        ],
    },
    {
        name => 'tab_bar',
        kind => 26,
        pix => 'TabBar',
        primary => 'on_change',
        doc => 'A row of tabs. The block receives the chosen index.',
        props => [
            { name => 'labels', key => 58, type => 'strs', pix => 'labels', default => [] },
            { name => 'active', key => 68, type => 'int', pix => 'active', default => 0 },
            { name => 'on_change', key => 39, handler => 'int', pix => 'onSelect', payload => 'index' },
        ],
    },
    {
        name => 'number_field',
        kind => 27,
        pix => 'NumberField',
        primary => 'on_change',
        doc => 'A field for a number: enter or leaving it commits, text that is not a number is dropped. `min`/`max` both 0 is unbounded, `step` 0 is free.',
        props => [
            { name => 'value', key => 37, type => 'num', pix => 'value', pos => 1 },
            { name => 'min', key => 59, type => 'num', pix => 'min', default => 0.0 },
            { name => 'max', key => 60, type => 'num', pix => 'max', default => 0.0 },
            { name => 'step', key => 66, type => 'num', pix => 'step', default => 0.0 },
            { name => 'placeholder', key => 38, type => 'str', pix => 'placeholder', default => '' },
            { name => 'on_change', key => 39, handler => 'float', pix => 'onChange', payload => 'value' },
        ],
    },
    {
        name => 'int_field',
        kind => 28,
        pix => 'IntField',
        primary => 'on_change',
        doc => 'The same field for a whole number.',
        props => [
            { name => 'value', key => 37, type => 'int', pix => 'value', pos => 1 },
            { name => 'min', key => 59, type => 'int', pix => 'min', default => 0 },
            { name => 'max', key => 60, type => 'int', pix => 'max', default => 0 },
            { name => 'step', key => 66, type => 'int', pix => 'step', default => 1 },
            { name => 'placeholder', key => 38, type => 'str', pix => 'placeholder', default => '' },
            { name => 'on_change', key => 39, handler => 'int', pix => 'onChange', payload => 'value' },
        ],
    },
    {
        name => 'link',
        kind => 29,
        pix => 'Link',
        doc => 'Text that opens a page when clicked. There is no handler: opening a page is not the app\'s state.',
        props => [
            { name => 'label', key => 32, type => 'str', pix => 'text', pos => 1 },
            { name => 'url', key => 69, type => 'str', pix => 'url', pos => 1 },
            { name => 'size', key => 17, type => 'num', pix => 'fontSize', default => 0.0 },
        ],
    },
    {
        name => 'spinner',
        kind => 30,
        pix => 'Spinner',
        doc => 'A turning ring, for work with no known length.',
        props => [
            { name => 'size', key => 17, type => 'num', pix => 'size', default => 0.0 },
        ],
    },
    {
        name => 'spacer',
        kind => 31,
        pix => 'Spacer',
        doc => 'Takes the space its parent has left over; 0 is one share.',
        props => [
            { name => 'grow', key => 20, type => 'num', pix => 'grow', default => 0.0 },
        ],
    },
    {
        name => 'divider',
        kind => 32,
        pix => 'Divider',
        doc => 'A rule across its parent: level in a column, upright in a row.',
        props => [
            { name => 'color', key => 18, type => 'str', pix => 'color', default => '' },
            { name => 'thickness', key => 70, type => 'num', pix => 'thickness', default => 0.0 },
        ],
    },
    {
        name => 'canvas',
        kind => 33,
        pix => 'Canvas',
        paints => 1,
        native => 'size',
        doc => 'A grid of virtual pixels, painted by the commands written in its block. A color here is a NUMBER: the index of a color in `palette`, which is how drawing code written for a pixel machine ports line for line. `scale` is how many logical pixels one virtual pixel takes.',
        props => [
            { name => 'width', key => 1, type => 'int', pix => 'width', pos => 1 },
            { name => 'height', key => 2, type => 'int', pix => 'height', pos => 1 },
            { name => 'scale', key => 71, type => 'int', pix => 'scale', default => 1 },
            { name => 'background', key => 27, type => 'int', pix => 'background', default => 0 },
            { name => 'palette', key => 72, type => 'strs', pix => 'palette', default => [] },
        ],
    },
);
our %ELEMENT = map { $_->{name} => $_ } @ELEMENTS;

# The canvas's drawing commands. Not elements: no kind, no handle, no
# keywords that every element takes, and no meaning outside the canvas
# they are written in.
our @OPS = (
    { name => 'pixel', pix => 'Pixel', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'line', pix => 'Line', params => [{ name => 'x1', pix => 'x1', type => 'int' }, { name => 'y1', pix => 'y1', type => 'int' }, { name => 'x2', pix => 'x2', type => 'int' }, { name => 'y2', pix => 'y2', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'rect', pix => 'Rect', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'w', pix => 'w', type => 'int' }, { name => 'h', pix => 'h', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'rect_outline', pix => 'RectOutline', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'w', pix => 'w', type => 'int' }, { name => 'h', pix => 'h', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'circle', pix => 'Circle', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'r', pix => 'r', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'circle_outline', pix => 'CircleOutline', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'r', pix => 'r', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'triangle', pix => 'Triangle', params => [{ name => 'x1', pix => 'x1', type => 'int' }, { name => 'y1', pix => 'y1', type => 'int' }, { name => 'x2', pix => 'x2', type => 'int' }, { name => 'y2', pix => 'y2', type => 'int' }, { name => 'x3', pix => 'x3', type => 'int' }, { name => 'y3', pix => 'y3', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'triangle_outline', pix => 'TriangleOutline', params => [{ name => 'x1', pix => 'x1', type => 'int' }, { name => 'y1', pix => 'y1', type => 'int' }, { name => 'x2', pix => 'x2', type => 'int' }, { name => 'y2', pix => 'y2', type => 'int' }, { name => 'x3', pix => 'x3', type => 'int' }, { name => 'y3', pix => 'y3', type => 'int' }, { name => 'color', pix => 'color', type => 'int' }] },
    { name => 'sprite', pix => 'Sprite', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'source', pix => 'source', type => 'str' }, { name => 'u', pix => 'u', type => 'int' }, { name => 'v', pix => 'v', type => 'int' }, { name => 'w', pix => 'w', type => 'int' }, { name => 'h', pix => 'h', type => 'int' }, { name => 'colkey', pix => 'colkey', type => 'int', default => '-1' }, { name => 'flip_x', pix => 'flipX', type => 'bool', default => 'false' }, { name => 'flip_y', pix => 'flipY', type => 'bool', default => 'false' }] },
    { name => 'pixel_text', pix => 'PixelText', params => [{ name => 'x', pix => 'x', type => 'int' }, { name => 'y', pix => 'y', type => 'int' }, { name => 'text', pix => 'text', type => 'str' }, { name => 'color', pix => 'color', type => 'int' }] },
);
our %OP = map { $_->{name} => $_ } @OPS;

1;
