// Code generated by tools/gen from crates/yokan-stdlib/stdlib.toml. DO NOT EDIT.
// Edit the manifest and run `go run ./tools/gen`.

package check

// The framework's own standard library, and what each call does that
// a view may not: the same list the package exports, kept here so the
// checker needs no import of it.
var stdlibNames = map[string]string{
	"AudioPlay":         "plays a sound",
	"AudioStop":         "plays a sound",
	"ClipboardGetText":  "reads or writes the clipboard",
	"ClipboardSetText":  "reads or writes the clipboard",
	"NotifySend":        "sends a notification",
	"OpenDialog":        "asks a person",
	"SaveDialog":        "asks a person",
	"SqliteExec":        "reads or writes a database",
	"SqliteQueryInt":    "reads or writes a database",
	"SqliteQueryIntOr":  "reads or writes a database",
	"SqliteQueryRows":   "reads or writes a database",
	"SqliteQueryRowsOr": "reads or writes a database",
	"SqliteQueryText":   "reads or writes a database",
	"SqliteQueryTextOr": "reads or writes a database",
}
