// Code generated by tools/gen from crates/pixie-capi/elements.toml. DO NOT EDIT.
// Edit the table and run `go run ./tools/gen`.

package gomamochi

import "github.com/i2y/yokan/gomamochi/internal/door"

// The numbers the two sides of the engine's C face count with.
const (
	kindText        = 1
	kindButton      = 2
	kindTextField   = 3
	kindColumn      = 4
	kindRow         = 5
	kindGrid        = 6
	kindGridCell    = 7
	kindStack       = 8
	kindScrollView  = 9
	kindHScrollView = 10
	kindDataTable   = 11
	kindModal       = 12
	kindListView    = 13
	kindTable       = 14
	kindImage       = 15
	kindSvg         = 16
	kindBarChart    = 17
	kindLineChart   = 18
	kindProgress    = 19
	kindCheckbox    = 20
	kindSwitch      = 21
	kindSlider      = 22
	kindSelect      = 23
	kindRadioGroup  = 24
	kindSegmented   = 25
	kindTabBar      = 26
	kindNumberField = 27
	kindIntField    = 28
	kindLink        = 29
	kindSpinner     = 30
	kindSpacer      = 31
	kindDivider     = 32
	kindCanvas      = 33
)

// The keyword arguments, numbered once across every element.
const (
	kWidth            = 1
	kHeight           = 2
	kMinWidth         = 3
	kMaxWidth         = 4
	kDisabled         = 5
	kTheme            = 6
	kAnimate          = 7
	kEasing           = 8
	kEnter            = 9
	kExit             = 10
	kColSpan          = 11
	kRowSpan          = 12
	kRole             = 13
	kA11yLabel        = 14
	kTooltip          = 15
	kText             = 16
	kSize             = 17
	kColor            = 18
	kAlign            = 19
	kGrow             = 20
	kBold             = 21
	kItalic           = 22
	kMono             = 23
	kUnderline        = 24
	kWrap             = 25
	kMaxLines         = 26
	kBackground       = 27
	kPadding          = 28
	kBorderRadius     = 29
	kBorderWidth      = 30
	kBorderColor      = 31
	kLabel            = 32
	kOnClick          = 33
	kHoverBackground  = 34
	kActiveBackground = 35
	kBasis            = 36
	kValue            = 37
	kPlaceholder      = 38
	kOnChange         = 39
	kOnSubmit         = 40
	kMultiline        = 41
	kRows             = 42
	kSpacing          = 43
	kColumns          = 44
	kOpen             = 45
	kCount            = 46
	kRow              = 47
	kItemHeight       = 48
	kVirtualized      = 49
	kWidths           = 50
	kSelected         = 51
	kOnSelect         = 52
	kSort             = 53
	kDescending       = 54
	kOnSort           = 55
	kSource           = 56
	kData             = 57
	kLabels           = 58
	kMin              = 59
	kMax              = 60
	kAxis             = 61
	kSeries           = 62
	kColors           = 63
	kIndeterminate    = 64
	kChecked          = 65
	kStep             = 66
	kOptions          = 67
	kActive           = 68
	kUrl              = 69
	kThickness        = 70
	kScale            = 71
	kPalette          = 72
)

// The keyword arguments every element takes, under one name and one
// meaning. A rider that was written is written to the engine whatever
// its value — a width of 0 still makes a box, and one nobody wrote does
// not — so each remembers whether it was.
type riders struct {
	set       uint32
	width     float64
	height    float64
	minWidth  float64
	maxWidth  float64
	disabled  bool
	theme     string
	animate   float64
	easing    string
	enter     bool
	exit      bool
	colSpan   int
	rowSpan   int
	role      string
	a11yLabel string
	tooltip   string
}

const (
	rWidth uint32 = 1 << iota
	rHeight
	rMinWidth
	rMaxWidth
	rDisabled
	rTheme
	rAnimate
	rEasing
	rEnter
	rExit
	rColSpan
	rRowSpan
	rRole
	rA11yLabel
	rTooltip
)

func (r *riders) write(el int64) {
	if r.set&rWidth != 0 {
		door.Num(el, kWidth, r.width)
	}
	if r.set&rHeight != 0 {
		door.Num(el, kHeight, r.height)
	}
	if r.set&rMinWidth != 0 {
		door.Num(el, kMinWidth, r.minWidth)
	}
	if r.set&rMaxWidth != 0 {
		door.Num(el, kMaxWidth, r.maxWidth)
	}
	if r.set&rDisabled != 0 {
		door.Bool(el, kDisabled, r.disabled)
	}
	if r.set&rTheme != 0 {
		door.Str(el, kTheme, r.theme)
	}
	if r.set&rAnimate != 0 {
		door.Num(el, kAnimate, r.animate)
	}
	if r.set&rEasing != 0 {
		door.Str(el, kEasing, r.easing)
	}
	if r.set&rEnter != 0 {
		door.Bool(el, kEnter, r.enter)
	}
	if r.set&rExit != 0 {
		door.Bool(el, kExit, r.exit)
	}
	if r.set&rColSpan != 0 {
		door.Int(el, kColSpan, int64(r.colSpan))
	}
	if r.set&rRowSpan != 0 {
		door.Int(el, kRowSpan, int64(r.rowSpan))
	}
	if r.set&rRole != 0 {
		door.Str(el, kRole, r.role)
	}
	if r.set&rA11yLabel != 0 {
		door.Str(el, kA11yLabel, r.a11yLabel)
	}
	if r.set&rTooltip != 0 {
		door.Str(el, kTooltip, r.tooltip)
	}
}

// box carries the riders and the methods that set them, promoted into
// every element; `self` is the element, so a chain keeps its type. An
// element whose own keyword has the same name (a button's width) has a
// method of its own that wins over the rider's.
type box[T any] struct {
	self T
	rd   riders
}

func (b *box[T]) Width(v float64) T  { b.rd.width, b.rd.set = v, b.rd.set|rWidth; return b.self }
func (b *box[T]) Height(v float64) T { b.rd.height, b.rd.set = v, b.rd.set|rHeight; return b.self }
func (b *box[T]) MinWidth(v float64) T {
	b.rd.minWidth, b.rd.set = v, b.rd.set|rMinWidth
	return b.self
}
func (b *box[T]) MaxWidth(v float64) T {
	b.rd.maxWidth, b.rd.set = v, b.rd.set|rMaxWidth
	return b.self
}
func (b *box[T]) Disabled(v bool) T   { b.rd.disabled, b.rd.set = v, b.rd.set|rDisabled; return b.self }
func (b *box[T]) Theme(v string) T    { b.rd.theme, b.rd.set = v, b.rd.set|rTheme; return b.self }
func (b *box[T]) Animate(v float64) T { b.rd.animate, b.rd.set = v, b.rd.set|rAnimate; return b.self }
func (b *box[T]) Easing(v string) T   { b.rd.easing, b.rd.set = v, b.rd.set|rEasing; return b.self }
func (b *box[T]) Enter(v bool) T      { b.rd.enter, b.rd.set = v, b.rd.set|rEnter; return b.self }
func (b *box[T]) Exit(v bool) T       { b.rd.exit, b.rd.set = v, b.rd.set|rExit; return b.self }
func (b *box[T]) ColSpan(v int) T     { b.rd.colSpan, b.rd.set = v, b.rd.set|rColSpan; return b.self }
func (b *box[T]) RowSpan(v int) T     { b.rd.rowSpan, b.rd.set = v, b.rd.set|rRowSpan; return b.self }
func (b *box[T]) Role(v string) T     { b.rd.role, b.rd.set = v, b.rd.set|rRole; return b.self }
func (b *box[T]) A11yLabel(v string) T {
	b.rd.a11yLabel, b.rd.set = v, b.rd.set|rA11yLabel
	return b.self
}
func (b *box[T]) Tooltip(v string) T { b.rd.tooltip, b.rd.set = v, b.rd.set|rTooltip; return b.self }

// TextEl: A run of text. `wrap` is "", "nowrap" or "ellipsis"; a background with
// padding and a radius makes a pill.
type TextEl struct {
	box[*TextEl]
	text         string
	size         float64
	color        string
	align        string
	grow         float64
	bold         bool
	italic       bool
	mono         bool
	underline    bool
	wrap         string
	maxLines     int
	width        float64
	background   string
	padding      float64
	borderRadius float64
	borderWidth  float64
	borderColor  string
}

// Text is a new text.
func Text(text string) *TextEl {
	e := &TextEl{text: text}
	e.self = e
	return e
}

func (e *TextEl) Size(v float64) *TextEl         { e.size = v; return e }
func (e *TextEl) Color(v string) *TextEl         { e.color = v; return e }
func (e *TextEl) Align(v string) *TextEl         { e.align = v; return e }
func (e *TextEl) Grow(v float64) *TextEl         { e.grow = v; return e }
func (e *TextEl) Bold(v bool) *TextEl            { e.bold = v; return e }
func (e *TextEl) Italic(v bool) *TextEl          { e.italic = v; return e }
func (e *TextEl) Mono(v bool) *TextEl            { e.mono = v; return e }
func (e *TextEl) Underline(v bool) *TextEl       { e.underline = v; return e }
func (e *TextEl) Wrap(v string) *TextEl          { e.wrap = v; return e }
func (e *TextEl) MaxLines(v int) *TextEl         { e.maxLines = v; return e }
func (e *TextEl) Width(v float64) *TextEl        { e.width = v; return e }
func (e *TextEl) Background(v string) *TextEl    { e.background = v; return e }
func (e *TextEl) Padding(v float64) *TextEl      { e.padding = v; return e }
func (e *TextEl) BorderRadius(v float64) *TextEl { e.borderRadius = v; return e }
func (e *TextEl) BorderWidth(v float64) *TextEl  { e.borderWidth = v; return e }
func (e *TextEl) BorderColor(v string) *TextEl   { e.borderColor = v; return e }

func (e *TextEl) emit() int64 {
	el := door.El(kindText)
	door.Str(el, kText, e.text)
	if e.size != 0 {
		door.Num(el, kSize, e.size)
	}
	if e.color != "" {
		door.Str(el, kColor, e.color)
	}
	if e.align != "" {
		door.Str(el, kAlign, e.align)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.bold {
		door.Bool(el, kBold, e.bold)
	}
	if e.italic {
		door.Bool(el, kItalic, e.italic)
	}
	if e.mono {
		door.Bool(el, kMono, e.mono)
	}
	if e.underline {
		door.Bool(el, kUnderline, e.underline)
	}
	if e.wrap != "" {
		door.Str(el, kWrap, e.wrap)
	}
	if e.maxLines != 0 {
		door.Int(el, kMaxLines, int64(e.maxLines))
	}
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.background != "" {
		door.Str(el, kBackground, e.background)
	}
	if e.padding != 0 {
		door.Num(el, kPadding, e.padding)
	}
	if e.borderRadius != 0 {
		door.Num(el, kBorderRadius, e.borderRadius)
	}
	if e.borderWidth != 0 {
		door.Num(el, kBorderWidth, e.borderWidth)
	}
	if e.borderColor != "" {
		door.Str(el, kBorderColor, e.borderColor)
	}
	e.rd.write(el)
	return door.End(el)
}

// ButtonEl: A button. The block runs when it is pressed.
type ButtonEl struct {
	box[*ButtonEl]
	label            string
	onClick          func()
	width            float64
	height           float64
	size             float64
	background       string
	grow             float64
	color            string
	hoverBackground  string
	activeBackground string
	borderRadius     float64
	borderWidth      float64
	borderColor      string
	basis            float64
}

// Button is a new button.
func Button(label string) *ButtonEl {
	e := &ButtonEl{label: label}
	e.self = e
	return e
}

func (e *ButtonEl) OnClick(v func()) *ButtonEl          { e.onClick = v; return e }
func (e *ButtonEl) Width(v float64) *ButtonEl           { e.width = v; return e }
func (e *ButtonEl) Height(v float64) *ButtonEl          { e.height = v; return e }
func (e *ButtonEl) Size(v float64) *ButtonEl            { e.size = v; return e }
func (e *ButtonEl) Background(v string) *ButtonEl       { e.background = v; return e }
func (e *ButtonEl) Grow(v float64) *ButtonEl            { e.grow = v; return e }
func (e *ButtonEl) Color(v string) *ButtonEl            { e.color = v; return e }
func (e *ButtonEl) HoverBackground(v string) *ButtonEl  { e.hoverBackground = v; return e }
func (e *ButtonEl) ActiveBackground(v string) *ButtonEl { e.activeBackground = v; return e }
func (e *ButtonEl) BorderRadius(v float64) *ButtonEl    { e.borderRadius = v; return e }
func (e *ButtonEl) BorderWidth(v float64) *ButtonEl     { e.borderWidth = v; return e }
func (e *ButtonEl) BorderColor(v string) *ButtonEl      { e.borderColor = v; return e }
func (e *ButtonEl) Basis(v float64) *ButtonEl           { e.basis = v; return e }

func (e *ButtonEl) emit() int64 {
	el := door.El(kindButton)
	door.Str(el, kLabel, e.label)
	if f := e.onClick; f != nil {
		door.Handler(el, kOnClick, f)
	}
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if e.size != 0 {
		door.Num(el, kSize, e.size)
	}
	if e.background != "" {
		door.Str(el, kBackground, e.background)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.color != "" {
		door.Str(el, kColor, e.color)
	}
	if e.hoverBackground != "" {
		door.Str(el, kHoverBackground, e.hoverBackground)
	}
	if e.activeBackground != "" {
		door.Str(el, kActiveBackground, e.activeBackground)
	}
	if e.borderRadius != 0 {
		door.Num(el, kBorderRadius, e.borderRadius)
	}
	if e.borderWidth != 0 {
		door.Num(el, kBorderWidth, e.borderWidth)
	}
	if e.borderColor != "" {
		door.Str(el, kBorderColor, e.borderColor)
	}
	if e.basis != 0 {
		door.Num(el, kBasis, e.basis)
	}
	e.rd.write(el)
	return door.End(el)
}

// TextFieldEl: A line a person types into. `on_change` fires per keystroke, `on_submit`
// when they press enter; `multiline` makes it a paragraph field.
type TextFieldEl struct {
	box[*TextFieldEl]
	value       string
	placeholder string
	onChange    func(string)
	onSubmit    func(string)
	multiline   bool
	rows        float64
}

// TextField is a new text_field.
func TextField(value string) *TextFieldEl {
	e := &TextFieldEl{value: value}
	e.self = e
	return e
}

func (e *TextFieldEl) Placeholder(v string) *TextFieldEl    { e.placeholder = v; return e }
func (e *TextFieldEl) OnChange(v func(string)) *TextFieldEl { e.onChange = v; return e }
func (e *TextFieldEl) OnSubmit(v func(string)) *TextFieldEl { e.onSubmit = v; return e }
func (e *TextFieldEl) Multiline(v bool) *TextFieldEl        { e.multiline = v; return e }
func (e *TextFieldEl) Rows(v float64) *TextFieldEl          { e.rows = v; return e }

func (e *TextFieldEl) emit() int64 {
	el := door.El(kindTextField)
	door.Str(el, kValue, e.value)
	if e.placeholder != "" {
		door.Str(el, kPlaceholder, e.placeholder)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(door.EventText()) })
	}
	if f := e.onSubmit; f != nil {
		door.Handler(el, kOnSubmit, func() { f(door.EventText()) })
	}
	if e.multiline {
		door.Bool(el, kMultiline, e.multiline)
	}
	if e.rows != 0 {
		door.Num(el, kRows, e.rows)
	}
	e.rd.write(el)
	return door.End(el)
}

// ColumnEl: Its children down the page.
type ColumnEl struct {
	box[*ColumnEl]
	spacing      float64
	padding      float64
	background   string
	grow         float64
	borderRadius float64
	borderWidth  float64
	borderColor  string
	kids         []Element
}

// Column is a new column.
func Column(kids ...Element) *ColumnEl {
	e := &ColumnEl{spacing: -1, kids: kids}
	e.self = e
	return e
}

func (e *ColumnEl) Spacing(v float64) *ColumnEl      { e.spacing = v; return e }
func (e *ColumnEl) Padding(v float64) *ColumnEl      { e.padding = v; return e }
func (e *ColumnEl) Background(v string) *ColumnEl    { e.background = v; return e }
func (e *ColumnEl) Grow(v float64) *ColumnEl         { e.grow = v; return e }
func (e *ColumnEl) BorderRadius(v float64) *ColumnEl { e.borderRadius = v; return e }
func (e *ColumnEl) BorderWidth(v float64) *ColumnEl  { e.borderWidth = v; return e }
func (e *ColumnEl) BorderColor(v string) *ColumnEl   { e.borderColor = v; return e }

func (e *ColumnEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindColumn)
	if e.spacing != -1 {
		door.Num(el, kSpacing, e.spacing)
	}
	if e.padding != 0 {
		door.Num(el, kPadding, e.padding)
	}
	if e.background != "" {
		door.Str(el, kBackground, e.background)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.borderRadius != 0 {
		door.Num(el, kBorderRadius, e.borderRadius)
	}
	if e.borderWidth != 0 {
		door.Num(el, kBorderWidth, e.borderWidth)
	}
	if e.borderColor != "" {
		door.Str(el, kBorderColor, e.borderColor)
	}
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// RowEl: Its children across the page.
type RowEl struct {
	box[*RowEl]
	spacing      float64
	padding      float64
	background   string
	grow         float64
	borderRadius float64
	borderWidth  float64
	borderColor  string
	kids         []Element
}

// Row is a new row.
func Row(kids ...Element) *RowEl {
	e := &RowEl{spacing: -1, kids: kids}
	e.self = e
	return e
}

func (e *RowEl) Spacing(v float64) *RowEl      { e.spacing = v; return e }
func (e *RowEl) Padding(v float64) *RowEl      { e.padding = v; return e }
func (e *RowEl) Background(v string) *RowEl    { e.background = v; return e }
func (e *RowEl) Grow(v float64) *RowEl         { e.grow = v; return e }
func (e *RowEl) BorderRadius(v float64) *RowEl { e.borderRadius = v; return e }
func (e *RowEl) BorderWidth(v float64) *RowEl  { e.borderWidth = v; return e }
func (e *RowEl) BorderColor(v string) *RowEl   { e.borderColor = v; return e }

func (e *RowEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindRow)
	if e.spacing != -1 {
		door.Num(el, kSpacing, e.spacing)
	}
	if e.padding != 0 {
		door.Num(el, kPadding, e.padding)
	}
	if e.background != "" {
		door.Str(el, kBackground, e.background)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.borderRadius != 0 {
		door.Num(el, kBorderRadius, e.borderRadius)
	}
	if e.borderWidth != 0 {
		door.Num(el, kBorderWidth, e.borderWidth)
	}
	if e.borderColor != "" {
		door.Str(el, kBorderColor, e.borderColor)
	}
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// GridEl: Its children on tracks. `columns` counts the tracks; `col_span` on a
// child covers more than one.
type GridEl struct {
	box[*GridEl]
	columns      int
	rows         int
	spacing      float64
	padding      float64
	background   string
	grow         float64
	borderRadius float64
	borderWidth  float64
	borderColor  string
	kids         []Element
}

// Grid is a new grid.
func Grid(kids ...Element) *GridEl {
	e := &GridEl{columns: 2, spacing: -1, kids: kids}
	e.self = e
	return e
}

func (e *GridEl) Columns(v int) *GridEl          { e.columns = v; return e }
func (e *GridEl) Rows(v int) *GridEl             { e.rows = v; return e }
func (e *GridEl) Spacing(v float64) *GridEl      { e.spacing = v; return e }
func (e *GridEl) Padding(v float64) *GridEl      { e.padding = v; return e }
func (e *GridEl) Background(v string) *GridEl    { e.background = v; return e }
func (e *GridEl) Grow(v float64) *GridEl         { e.grow = v; return e }
func (e *GridEl) BorderRadius(v float64) *GridEl { e.borderRadius = v; return e }
func (e *GridEl) BorderWidth(v float64) *GridEl  { e.borderWidth = v; return e }
func (e *GridEl) BorderColor(v string) *GridEl   { e.borderColor = v; return e }

func (e *GridEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindGrid)
	if e.columns != 2 {
		door.Int(el, kColumns, int64(e.columns))
	}
	if e.rows != 0 {
		door.Int(el, kRows, int64(e.rows))
	}
	if e.spacing != -1 {
		door.Num(el, kSpacing, e.spacing)
	}
	if e.padding != 0 {
		door.Num(el, kPadding, e.padding)
	}
	if e.background != "" {
		door.Str(el, kBackground, e.background)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.borderRadius != 0 {
		door.Num(el, kBorderRadius, e.borderRadius)
	}
	if e.borderWidth != 0 {
		door.Num(el, kBorderWidth, e.borderWidth)
	}
	if e.borderColor != "" {
		door.Str(el, kBorderColor, e.borderColor)
	}
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// GridCellEl: The span written out: this and `col_span:` on the child itself are the
// same tree.
type GridCellEl struct {
	box[*GridCellEl]
	kids []Element
}

// GridCell is a new grid_cell.
func GridCell(kids ...Element) *GridCellEl {
	e := &GridCellEl{kids: kids}
	e.self = e
	return e
}

func (e *GridCellEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindGridCell)
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// StackEl: Its children on top of one another.
type StackEl struct {
	box[*StackEl]
	kids []Element
}

// Stack is a new stack.
func Stack(kids ...Element) *StackEl {
	e := &StackEl{kids: kids}
	e.self = e
	return e
}

func (e *StackEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindStack)
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// ScrollViewEl: A pane that scrolls when its children do not fit.
type ScrollViewEl struct {
	box[*ScrollViewEl]
	height float64
	kids   []Element
}

// ScrollView is a new scroll_view.
func ScrollView(kids ...Element) *ScrollViewEl {
	e := &ScrollViewEl{kids: kids}
	e.self = e
	return e
}

func (e *ScrollViewEl) Height(v float64) *ScrollViewEl { e.height = v; return e }

func (e *ScrollViewEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindScrollView)
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// HScrollViewEl: A pane that scrolls sideways.
type HScrollViewEl struct {
	box[*HScrollViewEl]
	kids []Element
}

// HScrollView is a new h_scroll_view.
func HScrollView(kids ...Element) *HScrollViewEl {
	e := &HScrollViewEl{kids: kids}
	e.self = e
	return e
}

func (e *HScrollViewEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindHScrollView)
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// DataTableEl: The first `row` child is the header; the later ones are data rows, shaded
// in alternation, in a frame that comes with the element.
type DataTableEl struct {
	box[*DataTableEl]
	kids []Element
}

// DataTable is a new data_table.
func DataTable(kids ...Element) *DataTableEl {
	e := &DataTableEl{kids: kids}
	e.self = e
	return e
}

func (e *DataTableEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindDataTable)
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// ModalEl: A panel over the rest of the window while `open`.
type ModalEl struct {
	box[*ModalEl]
	open bool
	kids []Element
}

// Modal is a new modal.
func Modal(kids ...Element) *ModalEl {
	e := &ModalEl{open: true, kids: kids}
	e.self = e
	return e
}

func (e *ModalEl) Open(v bool) *ModalEl { e.open = v; return e }

func (e *ModalEl) emit() int64 {
	// Children first, as an argument list is evaluated in every
	// sibling language; the dumps then read the same.
	ids := make([]int64, 0, len(e.kids))
	for _, k := range e.kids {
		if k != nil {
			ids = append(ids, k.emit())
		}
	}
	el := door.El(kindModal)
	if !e.open {
		door.Bool(el, kOpen, e.open)
	}
	door.Children(el, ids)
	e.rd.write(el)
	return door.End(el)
}

// ListViewEl: Rows built on demand: the builder is called for the rows in view, not for
// all of them.
type ListViewEl struct {
	box[*ListViewEl]
	count       int
	row         func(int) Element
	itemHeight  float64
	height      float64
	virtualized bool
	grow        float64
}

// ListView is a new list_view.
func ListView(count int, row func(int) Element) *ListViewEl {
	e := &ListViewEl{count: count, row: row, itemHeight: 24, virtualized: true}
	e.self = e
	return e
}

func (e *ListViewEl) ItemHeight(v float64) *ListViewEl { e.itemHeight = v; return e }
func (e *ListViewEl) Height(v float64) *ListViewEl     { e.height = v; return e }
func (e *ListViewEl) Virtualized(v bool) *ListViewEl   { e.virtualized = v; return e }
func (e *ListViewEl) Grow(v float64) *ListViewEl       { e.grow = v; return e }

func (e *ListViewEl) emit() int64 {
	el := door.El(kindListView)
	door.Int(el, kCount, int64(e.count))
	if row := e.row; row != nil {
		door.RowBuilder(el, kRow, func(i int64) int64 {
			r := row(int(i))
			if r == nil {
				return 0
			}
			return r.emit()
		})
	}
	if e.itemHeight != 24 {
		door.Num(el, kItemHeight, e.itemHeight)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if !e.virtualized {
		door.Bool(el, kVirtualized, e.virtualized)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	e.rd.write(el)
	return door.End(el)
}

// TableEl: A table whose rows are built on demand, laid on tracks whose shares are
// `widths`. `on_select` receives the row clicked, `on_sort` the header.
type TableEl struct {
	box[*TableEl]
	columns    []string
	count      int
	row        func(int) Element
	widths     []float64
	itemHeight float64
	height     float64
	grow       float64
	selected   int
	onSelect   func(int)
	sort       int
	descending bool
	onSort     func(int)
}

// Table is a new table.
func Table(columns []string, count int, row func(int) Element) *TableEl {
	e := &TableEl{columns: columns, count: count, row: row, itemHeight: 24, selected: -1, sort: -1}
	e.self = e
	return e
}

func (e *TableEl) Widths(v ...float64) *TableEl  { e.widths = v; return e }
func (e *TableEl) ItemHeight(v float64) *TableEl { e.itemHeight = v; return e }
func (e *TableEl) Height(v float64) *TableEl     { e.height = v; return e }
func (e *TableEl) Grow(v float64) *TableEl       { e.grow = v; return e }
func (e *TableEl) Selected(v int) *TableEl       { e.selected = v; return e }
func (e *TableEl) OnSelect(v func(int)) *TableEl { e.onSelect = v; return e }
func (e *TableEl) Sort(v int) *TableEl           { e.sort = v; return e }
func (e *TableEl) Descending(v bool) *TableEl    { e.descending = v; return e }
func (e *TableEl) OnSort(v func(int)) *TableEl   { e.onSort = v; return e }

func (e *TableEl) emit() int64 {
	el := door.El(kindTable)
	for _, v := range e.columns {
		door.PushStr(el, kColumns, v)
	}
	door.Int(el, kCount, int64(e.count))
	if row := e.row; row != nil {
		door.RowBuilder(el, kRow, func(i int64) int64 {
			r := row(int(i))
			if r == nil {
				return 0
			}
			return r.emit()
		})
	}
	for _, v := range e.widths {
		door.PushNum(el, kWidths, v)
	}
	if e.itemHeight != 24 {
		door.Num(el, kItemHeight, e.itemHeight)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	if e.selected != -1 {
		door.Int(el, kSelected, int64(e.selected))
	}
	if f := e.onSelect; f != nil {
		door.Handler(el, kOnSelect, func() { f(int(door.EventInt())) })
	}
	if e.sort != -1 {
		door.Int(el, kSort, int64(e.sort))
	}
	if e.descending {
		door.Bool(el, kDescending, e.descending)
	}
	if f := e.onSort; f != nil {
		door.Handler(el, kOnSort, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// ImageEl: A picture from a file.
type ImageEl struct {
	box[*ImageEl]
	source string
	width  float64
	height float64
}

// Image is a new image.
func Image(source string) *ImageEl {
	e := &ImageEl{source: source}
	e.self = e
	return e
}

func (e *ImageEl) Width(v float64) *ImageEl  { e.width = v; return e }
func (e *ImageEl) Height(v float64) *ImageEl { e.height = v; return e }

func (e *ImageEl) emit() int64 {
	el := door.El(kindImage)
	door.Str(el, kSource, e.source)
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	e.rd.write(el)
	return door.End(el)
}

// SvgEl: A drawing from an SVG file, painted at any size.
type SvgEl struct {
	box[*SvgEl]
	source string
	width  float64
	height float64
}

// Svg is a new svg.
func Svg(source string) *SvgEl {
	e := &SvgEl{source: source}
	e.self = e
	return e
}

func (e *SvgEl) Width(v float64) *SvgEl  { e.width = v; return e }
func (e *SvgEl) Height(v float64) *SvgEl { e.height = v; return e }

func (e *SvgEl) emit() int64 {
	el := door.El(kindSvg)
	door.Str(el, kSource, e.source)
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	e.rd.write(el)
	return door.End(el)
}

// BarChartEl: Bars. `min`/`max` both 0 take the range from the data; `axis` draws ticks
// and gridlines; `series` draws several groups.
type BarChartEl struct {
	box[*BarChartEl]
	data   []float64
	labels []string
	width  float64
	height float64
	min    float64
	max    float64
	axis   bool
	color  string
	series [][]float64
	colors []string
}

// BarChart is a new bar_chart.
func BarChart(data []float64) *BarChartEl {
	e := &BarChartEl{data: data}
	e.self = e
	return e
}

func (e *BarChartEl) Labels(v ...string) *BarChartEl   { e.labels = v; return e }
func (e *BarChartEl) Width(v float64) *BarChartEl      { e.width = v; return e }
func (e *BarChartEl) Height(v float64) *BarChartEl     { e.height = v; return e }
func (e *BarChartEl) Min(v float64) *BarChartEl        { e.min = v; return e }
func (e *BarChartEl) Max(v float64) *BarChartEl        { e.max = v; return e }
func (e *BarChartEl) Axis(v bool) *BarChartEl          { e.axis = v; return e }
func (e *BarChartEl) Color(v string) *BarChartEl       { e.color = v; return e }
func (e *BarChartEl) Series(v [][]float64) *BarChartEl { e.series = v; return e }
func (e *BarChartEl) Colors(v ...string) *BarChartEl   { e.colors = v; return e }

func (e *BarChartEl) emit() int64 {
	el := door.El(kindBarChart)
	for _, v := range e.data {
		door.PushNum(el, kData, v)
	}
	for _, v := range e.labels {
		door.PushStr(el, kLabels, v)
	}
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if e.min != 0 {
		door.Num(el, kMin, e.min)
	}
	if e.max != 0 {
		door.Num(el, kMax, e.max)
	}
	if e.axis {
		door.Bool(el, kAxis, e.axis)
	}
	if e.color != "" {
		door.Str(el, kColor, e.color)
	}
	for _, inner := range e.series {
		door.ListBreak(el, kSeries)
		for _, v := range inner {
			door.PushNum(el, kSeries, v)
		}
	}
	for _, v := range e.colors {
		door.PushStr(el, kColors, v)
	}
	e.rd.write(el)
	return door.End(el)
}

// LineChartEl: A line. Same arguments as the bars, and `series` draws several lines.
type LineChartEl struct {
	box[*LineChartEl]
	data   []float64
	labels []string
	width  float64
	height float64
	min    float64
	max    float64
	axis   bool
	color  string
	series [][]float64
	colors []string
}

// LineChart is a new line_chart.
func LineChart(data []float64) *LineChartEl {
	e := &LineChartEl{data: data}
	e.self = e
	return e
}

func (e *LineChartEl) Labels(v ...string) *LineChartEl   { e.labels = v; return e }
func (e *LineChartEl) Width(v float64) *LineChartEl      { e.width = v; return e }
func (e *LineChartEl) Height(v float64) *LineChartEl     { e.height = v; return e }
func (e *LineChartEl) Min(v float64) *LineChartEl        { e.min = v; return e }
func (e *LineChartEl) Max(v float64) *LineChartEl        { e.max = v; return e }
func (e *LineChartEl) Axis(v bool) *LineChartEl          { e.axis = v; return e }
func (e *LineChartEl) Color(v string) *LineChartEl       { e.color = v; return e }
func (e *LineChartEl) Series(v [][]float64) *LineChartEl { e.series = v; return e }
func (e *LineChartEl) Colors(v ...string) *LineChartEl   { e.colors = v; return e }

func (e *LineChartEl) emit() int64 {
	el := door.El(kindLineChart)
	for _, v := range e.data {
		door.PushNum(el, kData, v)
	}
	for _, v := range e.labels {
		door.PushStr(el, kLabels, v)
	}
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if e.min != 0 {
		door.Num(el, kMin, e.min)
	}
	if e.max != 0 {
		door.Num(el, kMax, e.max)
	}
	if e.axis {
		door.Bool(el, kAxis, e.axis)
	}
	if e.color != "" {
		door.Str(el, kColor, e.color)
	}
	for _, inner := range e.series {
		door.ListBreak(el, kSeries)
		for _, v := range inner {
			door.PushNum(el, kSeries, v)
		}
	}
	for _, v := range e.colors {
		door.PushStr(el, kColors, v)
	}
	e.rd.write(el)
	return door.End(el)
}

// ProgressEl: A track filled to `value` (0 to 1); `indeterminate` sweeps instead, for
// work with no known length.
type ProgressEl struct {
	box[*ProgressEl]
	value         float64
	width         float64
	height        float64
	label         string
	indeterminate bool
}

// Progress is a new progress.
func Progress(value float64) *ProgressEl {
	e := &ProgressEl{value: value}
	e.self = e
	return e
}

func (e *ProgressEl) Width(v float64) *ProgressEl      { e.width = v; return e }
func (e *ProgressEl) Height(v float64) *ProgressEl     { e.height = v; return e }
func (e *ProgressEl) Label(v string) *ProgressEl       { e.label = v; return e }
func (e *ProgressEl) Indeterminate(v bool) *ProgressEl { e.indeterminate = v; return e }

// A11yLabel is refused here: this element's own `label` is already the
// name a screen reader reads.
func (e *ProgressEl) A11yLabel(string) *ProgressEl {
	panic("this element's own `label` is already the name a screen reader reads; there is no second one to give")
}

func (e *ProgressEl) emit() int64 {
	el := door.El(kindProgress)
	door.Num(el, kValue, e.value)
	if e.width != 0 {
		door.Num(el, kWidth, e.width)
	}
	if e.height != 0 {
		door.Num(el, kHeight, e.height)
	}
	if e.label != "" {
		door.Str(el, kLabel, e.label)
	}
	if e.indeterminate {
		door.Bool(el, kIndeterminate, e.indeterminate)
	}
	e.rd.write(el)
	return door.End(el)
}

// CheckboxEl: A box a person ticks. The block receives the new state.
type CheckboxEl struct {
	box[*CheckboxEl]
	label    string
	checked  bool
	onChange func(bool)
}

// Checkbox is a new checkbox.
func Checkbox(label string) *CheckboxEl {
	e := &CheckboxEl{label: label}
	e.self = e
	return e
}

func (e *CheckboxEl) Checked(v bool) *CheckboxEl        { e.checked = v; return e }
func (e *CheckboxEl) OnChange(v func(bool)) *CheckboxEl { e.onChange = v; return e }

// A11yLabel is refused here: this element's own `label` is already the
// name a screen reader reads.
func (e *CheckboxEl) A11yLabel(string) *CheckboxEl {
	panic("this element's own `label` is already the name a screen reader reads; there is no second one to give")
}

func (e *CheckboxEl) emit() int64 {
	el := door.El(kindCheckbox)
	door.Str(el, kLabel, e.label)
	if e.checked {
		door.Bool(el, kChecked, e.checked)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(door.EventInt() != 0) })
	}
	e.rd.write(el)
	return door.End(el)
}

// SwitchEl: A switch a person flips. The block receives the new state.
type SwitchEl struct {
	box[*SwitchEl]
	label    string
	checked  bool
	onChange func(bool)
}

// Switch is a new switch.
func Switch(label string) *SwitchEl {
	e := &SwitchEl{label: label}
	e.self = e
	return e
}

func (e *SwitchEl) Checked(v bool) *SwitchEl        { e.checked = v; return e }
func (e *SwitchEl) OnChange(v func(bool)) *SwitchEl { e.onChange = v; return e }

// A11yLabel is refused here: this element's own `label` is already the
// name a screen reader reads.
func (e *SwitchEl) A11yLabel(string) *SwitchEl {
	panic("this element's own `label` is already the name a screen reader reads; there is no second one to give")
}

func (e *SwitchEl) emit() int64 {
	el := door.El(kindSwitch)
	door.Str(el, kLabel, e.label)
	if e.checked {
		door.Bool(el, kChecked, e.checked)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(door.EventInt() != 0) })
	}
	e.rd.write(el)
	return door.End(el)
}

// SliderEl: A track a person drags. The block receives the new number.
type SliderEl struct {
	box[*SliderEl]
	value    float64
	min      float64
	max      float64
	step     float64
	onChange func(float64)
}

// Slider is a new slider.
func Slider() *SliderEl {
	e := &SliderEl{max: 1}
	e.self = e
	return e
}

func (e *SliderEl) Value(v float64) *SliderEl          { e.value = v; return e }
func (e *SliderEl) Min(v float64) *SliderEl            { e.min = v; return e }
func (e *SliderEl) Max(v float64) *SliderEl            { e.max = v; return e }
func (e *SliderEl) Step(v float64) *SliderEl           { e.step = v; return e }
func (e *SliderEl) OnChange(v func(float64)) *SliderEl { e.onChange = v; return e }

func (e *SliderEl) emit() int64 {
	el := door.El(kindSlider)
	if e.value != 0 {
		door.Num(el, kValue, e.value)
	}
	if e.min != 0 {
		door.Num(el, kMin, e.min)
	}
	if e.max != 1 {
		door.Num(el, kMax, e.max)
	}
	if e.step != 0 {
		door.Num(el, kStep, e.step)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(door.EventNum()) })
	}
	e.rd.write(el)
	return door.End(el)
}

// SelectEl: A drop-down. The block receives the chosen index.
type SelectEl struct {
	box[*SelectEl]
	options  []string
	selected int
	onChange func(int)
}

// Select is a new select.
func Select() *SelectEl {
	e := &SelectEl{}
	e.self = e
	return e
}

func (e *SelectEl) Options(v ...string) *SelectEl  { e.options = v; return e }
func (e *SelectEl) Selected(v int) *SelectEl       { e.selected = v; return e }
func (e *SelectEl) OnChange(v func(int)) *SelectEl { e.onChange = v; return e }

func (e *SelectEl) emit() int64 {
	el := door.El(kindSelect)
	for _, v := range e.options {
		door.PushStr(el, kOptions, v)
	}
	if e.selected != 0 {
		door.Int(el, kSelected, int64(e.selected))
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// RadioGroupEl: A column of radio buttons. The block receives the chosen index.
type RadioGroupEl struct {
	box[*RadioGroupEl]
	options  []string
	selected int
	onChange func(int)
}

// RadioGroup is a new radio_group.
func RadioGroup() *RadioGroupEl {
	e := &RadioGroupEl{}
	e.self = e
	return e
}

func (e *RadioGroupEl) Options(v ...string) *RadioGroupEl  { e.options = v; return e }
func (e *RadioGroupEl) Selected(v int) *RadioGroupEl       { e.selected = v; return e }
func (e *RadioGroupEl) OnChange(v func(int)) *RadioGroupEl { e.onChange = v; return e }

func (e *RadioGroupEl) emit() int64 {
	el := door.El(kindRadioGroup)
	for _, v := range e.options {
		door.PushStr(el, kOptions, v)
	}
	if e.selected != 0 {
		door.Int(el, kSelected, int64(e.selected))
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// SegmentedEl: A row of joined toggle buttons. The block receives the chosen index.
type SegmentedEl struct {
	box[*SegmentedEl]
	options  []string
	selected int
	onChange func(int)
}

// Segmented is a new segmented.
func Segmented() *SegmentedEl {
	e := &SegmentedEl{}
	e.self = e
	return e
}

func (e *SegmentedEl) Options(v ...string) *SegmentedEl  { e.options = v; return e }
func (e *SegmentedEl) Selected(v int) *SegmentedEl       { e.selected = v; return e }
func (e *SegmentedEl) OnChange(v func(int)) *SegmentedEl { e.onChange = v; return e }

func (e *SegmentedEl) emit() int64 {
	el := door.El(kindSegmented)
	for _, v := range e.options {
		door.PushStr(el, kOptions, v)
	}
	if e.selected != 0 {
		door.Int(el, kSelected, int64(e.selected))
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// TabBarEl: A row of tabs. The block receives the chosen index.
type TabBarEl struct {
	box[*TabBarEl]
	labels   []string
	active   int
	onChange func(int)
}

// TabBar is a new tab_bar.
func TabBar() *TabBarEl {
	e := &TabBarEl{}
	e.self = e
	return e
}

func (e *TabBarEl) Labels(v ...string) *TabBarEl   { e.labels = v; return e }
func (e *TabBarEl) Active(v int) *TabBarEl         { e.active = v; return e }
func (e *TabBarEl) OnChange(v func(int)) *TabBarEl { e.onChange = v; return e }

func (e *TabBarEl) emit() int64 {
	el := door.El(kindTabBar)
	for _, v := range e.labels {
		door.PushStr(el, kLabels, v)
	}
	if e.active != 0 {
		door.Int(el, kActive, int64(e.active))
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// NumberFieldEl: A field for a number: enter or leaving it commits, text that is not a
// number is dropped. `min`/`max` both 0 is unbounded, `step` 0 is free.
type NumberFieldEl struct {
	box[*NumberFieldEl]
	value       float64
	min         float64
	max         float64
	step        float64
	placeholder string
	onChange    func(float64)
}

// NumberField is a new number_field.
func NumberField(value float64) *NumberFieldEl {
	e := &NumberFieldEl{value: value}
	e.self = e
	return e
}

func (e *NumberFieldEl) Min(v float64) *NumberFieldEl            { e.min = v; return e }
func (e *NumberFieldEl) Max(v float64) *NumberFieldEl            { e.max = v; return e }
func (e *NumberFieldEl) Step(v float64) *NumberFieldEl           { e.step = v; return e }
func (e *NumberFieldEl) Placeholder(v string) *NumberFieldEl     { e.placeholder = v; return e }
func (e *NumberFieldEl) OnChange(v func(float64)) *NumberFieldEl { e.onChange = v; return e }

func (e *NumberFieldEl) emit() int64 {
	el := door.El(kindNumberField)
	door.Num(el, kValue, e.value)
	if e.min != 0 {
		door.Num(el, kMin, e.min)
	}
	if e.max != 0 {
		door.Num(el, kMax, e.max)
	}
	if e.step != 0 {
		door.Num(el, kStep, e.step)
	}
	if e.placeholder != "" {
		door.Str(el, kPlaceholder, e.placeholder)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(door.EventNum()) })
	}
	e.rd.write(el)
	return door.End(el)
}

// IntFieldEl: The same field for a whole number.
type IntFieldEl struct {
	box[*IntFieldEl]
	value       int
	min         int
	max         int
	step        int
	placeholder string
	onChange    func(int)
}

// IntField is a new int_field.
func IntField(value int) *IntFieldEl {
	e := &IntFieldEl{value: value, step: 1}
	e.self = e
	return e
}

func (e *IntFieldEl) Min(v int) *IntFieldEl            { e.min = v; return e }
func (e *IntFieldEl) Max(v int) *IntFieldEl            { e.max = v; return e }
func (e *IntFieldEl) Step(v int) *IntFieldEl           { e.step = v; return e }
func (e *IntFieldEl) Placeholder(v string) *IntFieldEl { e.placeholder = v; return e }
func (e *IntFieldEl) OnChange(v func(int)) *IntFieldEl { e.onChange = v; return e }

func (e *IntFieldEl) emit() int64 {
	el := door.El(kindIntField)
	door.Int(el, kValue, int64(e.value))
	if e.min != 0 {
		door.Int(el, kMin, int64(e.min))
	}
	if e.max != 0 {
		door.Int(el, kMax, int64(e.max))
	}
	if e.step != 1 {
		door.Int(el, kStep, int64(e.step))
	}
	if e.placeholder != "" {
		door.Str(el, kPlaceholder, e.placeholder)
	}
	if f := e.onChange; f != nil {
		door.Handler(el, kOnChange, func() { f(int(door.EventInt())) })
	}
	e.rd.write(el)
	return door.End(el)
}

// LinkEl: Text that opens a page when clicked. There is no handler: opening a page
// is not the app's state.
type LinkEl struct {
	box[*LinkEl]
	label string
	url   string
	size  float64
}

// Link is a new link.
func Link(label string, url string) *LinkEl {
	e := &LinkEl{label: label, url: url}
	e.self = e
	return e
}

func (e *LinkEl) Size(v float64) *LinkEl { e.size = v; return e }

func (e *LinkEl) emit() int64 {
	el := door.El(kindLink)
	door.Str(el, kLabel, e.label)
	door.Str(el, kUrl, e.url)
	if e.size != 0 {
		door.Num(el, kSize, e.size)
	}
	e.rd.write(el)
	return door.End(el)
}

// SpinnerEl: A turning ring, for work with no known length.
type SpinnerEl struct {
	box[*SpinnerEl]
	size float64
}

// Spinner is a new spinner.
func Spinner() *SpinnerEl {
	e := &SpinnerEl{}
	e.self = e
	return e
}

func (e *SpinnerEl) Size(v float64) *SpinnerEl { e.size = v; return e }

func (e *SpinnerEl) emit() int64 {
	el := door.El(kindSpinner)
	if e.size != 0 {
		door.Num(el, kSize, e.size)
	}
	e.rd.write(el)
	return door.End(el)
}

// SpacerEl: Takes the space its parent has left over; 0 is one share.
type SpacerEl struct {
	box[*SpacerEl]
	grow float64
}

// Spacer is a new spacer.
func Spacer() *SpacerEl {
	e := &SpacerEl{}
	e.self = e
	return e
}

func (e *SpacerEl) Grow(v float64) *SpacerEl { e.grow = v; return e }

func (e *SpacerEl) emit() int64 {
	el := door.El(kindSpacer)
	if e.grow != 0 {
		door.Num(el, kGrow, e.grow)
	}
	e.rd.write(el)
	return door.End(el)
}

// DividerEl: A rule across its parent: level in a column, upright in a row.
type DividerEl struct {
	box[*DividerEl]
	color     string
	thickness float64
}

// Divider is a new divider.
func Divider() *DividerEl {
	e := &DividerEl{}
	e.self = e
	return e
}

func (e *DividerEl) Color(v string) *DividerEl      { e.color = v; return e }
func (e *DividerEl) Thickness(v float64) *DividerEl { e.thickness = v; return e }

func (e *DividerEl) emit() int64 {
	el := door.El(kindDivider)
	if e.color != "" {
		door.Str(el, kColor, e.color)
	}
	if e.thickness != 0 {
		door.Num(el, kThickness, e.thickness)
	}
	e.rd.write(el)
	return door.End(el)
}

// CanvasEl: A grid of virtual pixels, painted by the commands written in its block. A
// color here is a NUMBER: the index of a color in `palette`, which is how
// drawing code written for a pixel machine ports line for line. `scale` is
// how many logical pixels one virtual pixel takes.
type CanvasEl struct {
	box[*CanvasEl]
	width      int
	height     int
	scale      int
	background int
	palette    []string
	paint      func(*Painter)
}

// Canvas is a new canvas.
func Canvas(width int, height int) *CanvasEl {
	e := &CanvasEl{width: width, height: height, scale: 1}
	e.self = e
	return e
}

func (e *CanvasEl) Scale(v int) *CanvasEl         { e.scale = v; return e }
func (e *CanvasEl) Background(v int) *CanvasEl    { e.background = v; return e }
func (e *CanvasEl) Palette(v ...string) *CanvasEl { e.palette = v; return e }

// Paint is what the canvas draws: the commands written on the painter
// it is handed, in order.
func (e *CanvasEl) Paint(f func(*Painter)) *CanvasEl { e.paint = f; return e }

func (e *CanvasEl) emit() int64 {
	el := door.El(kindCanvas)
	door.Int(el, kWidth, int64(e.width))
	door.Int(el, kHeight, int64(e.height))
	if e.scale != 1 {
		door.Int(el, kScale, int64(e.scale))
	}
	if e.background != 0 {
		door.Int(el, kBackground, int64(e.background))
	}
	for _, v := range e.palette {
		door.PushStr(el, kPalette, v)
	}
	if e.paint != nil {
		e.paint(&Painter{el: el})
	}
	e.rd.write(el)
	return door.End(el)
}

// Painter is what a canvas's Paint closure draws with. A command is not
// an element: it takes none of the keywords every element takes,
// nothing can click it, and it means nothing outside the canvas it was
// written in. Every coordinate is a whole virtual pixel and every color
// is a NUMBER, the index of a color in the canvas's palette.
type Painter struct{ el int64 }

func (p *Painter) Pixel(x int, y int, color int) {
	door.OpPixel(p.el, int64(x), int64(y), int64(color))
}
func (p *Painter) Line(x1 int, y1 int, x2 int, y2 int, color int) {
	door.OpLine(p.el, int64(x1), int64(y1), int64(x2), int64(y2), int64(color))
}
func (p *Painter) Rect(x int, y int, w int, h int, color int) {
	door.OpRect(p.el, int64(x), int64(y), int64(w), int64(h), int64(color))
}
func (p *Painter) RectOutline(x int, y int, w int, h int, color int) {
	door.OpRectOutline(p.el, int64(x), int64(y), int64(w), int64(h), int64(color))
}
func (p *Painter) Circle(x int, y int, r int, color int) {
	door.OpCircle(p.el, int64(x), int64(y), int64(r), int64(color))
}
func (p *Painter) CircleOutline(x int, y int, r int, color int) {
	door.OpCircleOutline(p.el, int64(x), int64(y), int64(r), int64(color))
}
func (p *Painter) Triangle(x1 int, y1 int, x2 int, y2 int, x3 int, y3 int, color int) {
	door.OpTriangle(p.el, int64(x1), int64(y1), int64(x2), int64(y2), int64(x3), int64(y3), int64(color))
}
func (p *Painter) TriangleOutline(x1 int, y1 int, x2 int, y2 int, x3 int, y3 int, color int) {
	door.OpTriangleOutline(p.el, int64(x1), int64(y1), int64(x2), int64(y2), int64(x3), int64(y3), int64(color))
}
func (p *Painter) Sprite(x int, y int, source string, u int, v int, w int, h int, colkey int, flipX bool, flipY bool) {
	door.OpSprite(p.el, int64(x), int64(y), source, int64(u), int64(v), int64(w), int64(h), int64(colkey), flipX, flipY)
}
func (p *Painter) PixelText(x int, y int, text string, color int) {
	door.OpPixelText(p.el, int64(x), int64(y), text, int64(color))
}
