// Code generated by tools/gen from crates/yokan-stdlib/stdlib.toml. DO NOT EDIT.
// Edit the manifest and run `go run ./tools/gen`.

package gomamochi

// The framework's own standard library: what the engine mediates, one
// implementation that both runs reach through the C face, so a run
// under a script keeps a dialog answered by `file:` and a sound silent
// in both. Files, the network, JSON and the clock are Go's own.

import "github.com/i2y/yokan/gomamochi/internal/door"

// OpenDialog is `fs.open_dialog` in the manifest.
func OpenDialog(title string) string {
	door.StdReset()
	door.StdArgStr(title)
	door.StdCall(10)
	return door.StdText()
}

// SaveDialog is `fs.save_dialog` in the manifest.
func SaveDialog(name string) string {
	door.StdReset()
	door.StdArgStr(name)
	door.StdCall(11)
	return door.StdText()
}

// SqliteExec is `sqlite.exec` in the manifest.
func SqliteExec(path string, sql string, params ...string) int {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		return int(door.StdCall(17))
	}
	return int(door.StdCall(12))
}

// SqliteQueryText is `sqlite.query_text` in the manifest.
func SqliteQueryText(path string, sql string, params ...string) []string {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		door.StdCall(18)
		return door.StdList()
	}
	door.StdCall(13)
	return door.StdList()
}

// SqliteQueryInt is `sqlite.query_int` in the manifest.
func SqliteQueryInt(path string, sql string, params ...string) int {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		return int(door.StdCall(19))
	}
	return int(door.StdCall(14))
}

// SqliteQueryIntOr is `sqlite.query_int_or` in the manifest.
func SqliteQueryIntOr(path string, sql string, fallback int, params ...string) int {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	door.StdArgInt(int64(fallback))
	if len(params) > 0 {
		door.StdArgList(params)
		return int(door.StdCall(20))
	}
	return int(door.StdCall(15))
}

// SqliteQueryTextOr is `sqlite.query_text_or` in the manifest.
func SqliteQueryTextOr(path string, sql string, params ...string) []string {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		door.StdCall(21)
		return door.StdList()
	}
	door.StdCall(16)
	return door.StdList()
}

// SqliteQueryRows is `sqlite.query_rows` in the manifest.
func SqliteQueryRows(path string, sql string, params ...string) [][]string {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		door.StdCall(23)
		return door.StdRows()
	}
	door.StdCall(22)
	return door.StdRows()
}

// SqliteQueryRowsOr is `sqlite.query_rows_or` in the manifest.
func SqliteQueryRowsOr(path string, sql string, params ...string) [][]string {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgStr(sql)
	if len(params) > 0 {
		door.StdArgList(params)
		door.StdCall(25)
		return door.StdRows()
	}
	door.StdCall(24)
	return door.StdRows()
}

// ClipboardSetText is `clipboard.set_text` in the manifest.
func ClipboardSetText(text string) int {
	door.StdReset()
	door.StdArgStr(text)
	return int(door.StdCall(26))
}

// ClipboardGetText is `clipboard.get_text` in the manifest.
func ClipboardGetText() string {
	door.StdReset()
	door.StdCall(27)
	return door.StdText()
}

// AudioPlay is `audio.play` in the manifest.
func AudioPlay(path string, volume float64) int {
	door.StdReset()
	door.StdArgStr(path)
	door.StdArgNum(volume)
	return int(door.StdCall(32))
}

// AudioStop is `audio.stop` in the manifest.
func AudioStop() int {
	door.StdReset()
	return int(door.StdCall(33))
}

// NotifySend is `notify.send` in the manifest.
func NotifySend(title string, body string) {
	door.StdReset()
	door.StdArgStr(title)
	door.StdArgStr(body)
	door.StdCall(34)
}
