// Code generated by tools/gen from crates/pixie-capi/elements.toml. DO NOT EDIT.
// Edit the table and run `go run ./tools/gen`.

// Package symbols is the interpreter's view of the gomamochi package:
// every exported name as a reflect value, and a wrapper for each
// interface an interpreted type may implement.
package symbols

import (
	"reflect"

	gm "github.com/i2y/yokan/gomamochi"
)

// Symbols is what the host hands to interp.Use.
var Symbols = map[string]map[string]reflect.Value{}

func init() {
	Symbols["github.com/i2y/yokan/gomamochi/gomamochi"] = map[string]reflect.Value{
		"App":           reflect.ValueOf((*gm.App)(nil)),
		"_App":          reflect.ValueOf((*_gomamochi_App)(nil)),
		"AudioPlay":     reflect.ValueOf(gm.AudioPlay),
		"AudioStop":     reflect.ValueOf(gm.AudioStop),
		"BarChart":      reflect.ValueOf(gm.BarChart),
		"BarChartEl":    reflect.ValueOf((*gm.BarChartEl)(nil)),
		"Button":        reflect.ValueOf(gm.Button),
		"ButtonEl":      reflect.ValueOf((*gm.ButtonEl)(nil)),
		"Canvas":        reflect.ValueOf(gm.Canvas),
		"CanvasEl":      reflect.ValueOf((*gm.CanvasEl)(nil)),
		"Checkbox":      reflect.ValueOf(gm.Checkbox),
		"CheckboxEl":    reflect.ValueOf((*gm.CheckboxEl)(nil)),
		"Column":        reflect.ValueOf(gm.Column),
		"ColumnEl":      reflect.ValueOf((*gm.ColumnEl)(nil)),
		"DataTable":     reflect.ValueOf(gm.DataTable),
		"DataTableEl":   reflect.ValueOf((*gm.DataTableEl)(nil)),
		"Divider":       reflect.ValueOf(gm.Divider),
		"DividerEl":     reflect.ValueOf((*gm.DividerEl)(nil)),
		"Element":       reflect.ValueOf((*gm.Element)(nil)),
		"Every":         reflect.ValueOf(gm.Every),
		"Grid":          reflect.ValueOf(gm.Grid),
		"GridCell":      reflect.ValueOf(gm.GridCell),
		"GridCellEl":    reflect.ValueOf((*gm.GridCellEl)(nil)),
		"GridEl":        reflect.ValueOf((*gm.GridEl)(nil)),
		"HScrollView":   reflect.ValueOf(gm.HScrollView),
		"HScrollViewEl": reflect.ValueOf((*gm.HScrollViewEl)(nil)),
		"Image":         reflect.ValueOf(gm.Image),
		"ImageEl":       reflect.ValueOf((*gm.ImageEl)(nil)),
		"IntField":      reflect.ValueOf(gm.IntField),
		"IntFieldEl":    reflect.ValueOf((*gm.IntFieldEl)(nil)),
		"KeyDown":       reflect.ValueOf(gm.KeyDown),
		"KeyPressed":    reflect.ValueOf(gm.KeyPressed),
		"KeyReleased":   reflect.ValueOf(gm.KeyReleased),
		"LineChart":     reflect.ValueOf(gm.LineChart),
		"LineChartEl":   reflect.ValueOf((*gm.LineChartEl)(nil)),
		"Link":          reflect.ValueOf(gm.Link),
		"LinkEl":        reflect.ValueOf((*gm.LinkEl)(nil)),
		"ListView":      reflect.ValueOf(gm.ListView),
		"ListViewEl":    reflect.ValueOf((*gm.ListViewEl)(nil)),
		"MenuItem":      reflect.ValueOf(gm.MenuItem),
		"Modal":         reflect.ValueOf(gm.Modal),
		"ModalEl":       reflect.ValueOf((*gm.ModalEl)(nil)),
		"NumberField":   reflect.ValueOf(gm.NumberField),
		"NumberFieldEl": reflect.ValueOf((*gm.NumberFieldEl)(nil)),
		"OnFileDrop":    reflect.ValueOf(gm.OnFileDrop),
		"OnKey":         reflect.ValueOf(gm.OnKey),
		"Option":        reflect.ValueOf((*gm.Option)(nil)),
		"Padding":       reflect.ValueOf(gm.Padding),
		"Painter":       reflect.ValueOf((*gm.Painter)(nil)),
		"Progress":      reflect.ValueOf(gm.Progress),
		"ProgressEl":    reflect.ValueOf((*gm.ProgressEl)(nil)),
		"Quit":          reflect.ValueOf(gm.Quit),
		"RadioGroup":    reflect.ValueOf(gm.RadioGroup),
		"RadioGroupEl":  reflect.ValueOf((*gm.RadioGroupEl)(nil)),
		"Row":           reflect.ValueOf(gm.Row),
		"RowEl":         reflect.ValueOf((*gm.RowEl)(nil)),
		"Run":           reflect.ValueOf(gm.Run),
		"ScrollView":    reflect.ValueOf(gm.ScrollView),
		"ScrollViewEl":  reflect.ValueOf((*gm.ScrollViewEl)(nil)),
		"Segmented":     reflect.ValueOf(gm.Segmented),
		"SegmentedEl":   reflect.ValueOf((*gm.SegmentedEl)(nil)),
		"Select":        reflect.ValueOf(gm.Select),
		"SelectEl":      reflect.ValueOf((*gm.SelectEl)(nil)),
		"Shortcut":      reflect.ValueOf(gm.Shortcut),
		"Size":          reflect.ValueOf(gm.Size),
		"Slider":        reflect.ValueOf(gm.Slider),
		"SliderEl":      reflect.ValueOf((*gm.SliderEl)(nil)),
		"Spacer":        reflect.ValueOf(gm.Spacer),
		"SpacerEl":      reflect.ValueOf((*gm.SpacerEl)(nil)),
		"Spinner":       reflect.ValueOf(gm.Spinner),
		"SpinnerEl":     reflect.ValueOf((*gm.SpinnerEl)(nil)),
		"Stack":         reflect.ValueOf(gm.Stack),
		"StackEl":       reflect.ValueOf((*gm.StackEl)(nil)),
		"Svg":           reflect.ValueOf(gm.Svg),
		"SvgEl":         reflect.ValueOf((*gm.SvgEl)(nil)),
		"Switch":        reflect.ValueOf(gm.Switch),
		"SwitchEl":      reflect.ValueOf((*gm.SwitchEl)(nil)),
		"TabBar":        reflect.ValueOf(gm.TabBar),
		"TabBarEl":      reflect.ValueOf((*gm.TabBarEl)(nil)),
		"Table":         reflect.ValueOf(gm.Table),
		"TableEl":       reflect.ValueOf((*gm.TableEl)(nil)),
		"Task":          reflect.ValueOf(gm.Task),
		"Text":          reflect.ValueOf(gm.Text),
		"TextEl":        reflect.ValueOf((*gm.TextEl)(nil)),
		"TextField":     reflect.ValueOf(gm.TextField),
		"TextFieldEl":   reflect.ValueOf((*gm.TextFieldEl)(nil)),
		"Title":         reflect.ValueOf(gm.Title),
	}
}

// _gomamochi_App is an interface wrapper for App.
type _gomamochi_App struct {
	IValue interface{}
	WView  func() gm.Element
}

func (W _gomamochi_App) View() gm.Element { return W.WView() }
